### ISSUE TITLE
I get this error repeating in different tests!

### ISSUE THREAD

**Issue by mwlik** [gemartin99/Push_swap_tester#2]
Any idea plz!

P.S: I use the school Macs & 1337 (42)

<img width="713" alt="image" src="https://github.com/gemartin99/Push-Swap-Tester/assets/73129654/f433fe17-66a4-4d43-8782-742afe86441b">

**Comment by gemartin99** [comment]
Sorry for the delay in replying. The problem that appears is that the computers you are on do not have the atExit leaks library downloaded (or for some reason it does not work or seems to be missing), which is the command I use to check for leaks in the tester. You should check your program for leaks manually. I still recommend you to tell your campus staff in case it is a technical problem or a versioning problem.

**Comment by mwlik** [comment]
Thanks a lot for the response, I will proceed to close the issue.
