### ISSUE TITLE
Adding a new CONTROL ERRORS test

### ISSUE THREAD

**Issue by frenzla** [gemartin99/Push_swap_tester#3]
Loving your tester @gemartin99 ! Great job here.

For the sake of thoroughness, a new test could be added to CONTROL ERRORS: a non digit argument present within the arguments given.

Test N.1 tests a non digit argument, but only with one argument, not within a suite of arguments. Here the goal is to include the anomaly inside the arguments.

Example: `./push_swap "14 a 78"`

This should output "Error" and is not otherwise tested.

> p.s. This came from my own experience ;-) I submitted the project while it was passing all tests with Push-Swap-Tester. The evaluator came and tested this simple case `./push_swap "14 a 78"` : my project crashed. I had introduced an error while fixing last minute valgrind-revealed leaks. The tester did not detect the problem in my new version.
> I can provide the code if you want to check how the missing test went undetected.

I hope future students will be able to benefit from my error.

I include here a code snippet that could be easily included in your test file (taking inspiration from your test code blocks - I let you check if it's valid):

```
./push_swap "14 a 78" 2> test_check.txt
if [ -s "$FICHERO" ];then
while IFS= read -r line
do
  if [[ $line == "Error" ]]; then
  	printf "${GREEN}39.[OK] ${DEF_COLOR}\n";
  else
  	printf "${RED}39.[KO] ${DEF_COLOR}\n";
  	break
  fi
done < test_check.txt
else
	printf "${RED}39.[KO] ${DEF_COLOR}\n";
fi

rm -rf test_check.txt```

**Comment by gemartin99** [comment]
Oops sorry I didn't think of that possible case before. The tester has already been modified and I have added that possible case + some other similar cases. Thank you very much for explaining what happened to you and helping to improve the tester for future students to improve their project. I hope you have good luck in your future project delivery and get it approved. Best regards!
