### ISSUE TITLE
Little typo

### ISSUE THREAD

**Issue by Valentin-Anfossi** [gemartin99/Push_swap_tester#4]
First of all, thanks for your hard work, really appreciated !

I think there's a small typo in push_swap_test_linux.sh line 3714

`R=$(./push_swap $ARG | valgrind --leak-check=full ./checker $ARG > /dev/null 2>&1)`

I think its supposed to be 

`R=$(./push_swap $ARG | valgrind --leak-check=full ./checker_linux $ARG > /dev/null 2>&1)`

while I'm there, I also don't get the bonus test... 
In one (line 4850) sending "sa\n" on a stack made with "1" is supposed to print out error on output 2.
While in another (line 4981) also on a stack made with "1", passing a tons of operations (including "sa\n") is supposed to return "OK"

I guess returning "OK" is more aligned with the subject (sa isnt supposed to error out if the stack is 1 long, just "do nothing") but I'm curious now

**Comment by gemartin99** [comment]
Thanks for your comment and for contributing to the improvement of the tester, you are right, line 3714 should be checker_linux. It will be corrected right now. 

Regarding line 4850 and 4981, let me explain: It should only include a line break after the operation if in the next line there is another operation. That is, the last operation you make should not contain a line break. For error control I simply follow the checker provided by 42 and replicate its operation, in these cases this checker throws error. 

Thanks again and greetings from Barcelona.

**Comment by Valentin-Anfossi** [comment]
Ok I see, this makes sense. Thanks ! :)
